<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository {
	const OPTIONAL = 'optional';

	const BASE = 'base';

	public function findAll() {
		return $this->findBy([], ['billingDate' => 'desc']);
	}

	public function amountByState() {
		$amounts = $this->createQueryBuilder('i')
			->leftJoin('i.quote', 'q')
			->leftJoin('q.sections', 's')
			->leftJoin('s.items', 'it')

			->select('i.state, s.option, SUM(i.percentage/100 * s.rate * it.hours) AS amount')

			->groupBy('i.state, s.option')

			->getQuery()
			->getResult();

		$total = [];
		foreach ($amounts as $amount) {
			if (!isset($total[$amount['state']])) {
				$total[$amount['state']] = [
					self::OPTIONAL => 0,
					self::BASE => 0,
				];
			}
			$option = $amount['option'] ? self::OPTIONAL : self::BASE;
			$total[$amount['state']][$option] = $amount['amount'];
		}
		return $total;
	}
}
